details:
  everything_api : https://newsapi.org/v2/everything
  thl_api : https://newsapi.org/v2/top-headlines



categories:
  1 : Business
  2 : Health
  3 : Technology
  4 : Science
  5 : Sports

headers:
  1 : S.NO
  2 : Country Name

headers_val:
  1 : s.no
  2 : type

top_headers:
  1 : Source Name
  2 : Author
  3 : Title
  4 : Published At
  5 : description


days_limit:
  days : 30


language:
  1 : Arabic
  2 : German
  3 : English
  4 : Spanish
  5 : French
  6 : Hebrew
  7 : Italian
  8 : Dutch
  9 : Norwegian
  10 : Portuguese
  11 : Russian
  12 : Swedish
  13 : Urdu
  14 : Chinese

language_codes:
  1 : ar
  2: de
  3: en
  4: es
  5: fr
  6: he
  7: it
  8: nl
  9: no
  10: pt
  11: ru
  12: sv
  13: ud
  14: zh


sort_val:
  1: relevancy
  2: popularity
  3: publishedAt


country_var:
  1: United Arab Emirates
  2: Argentina
  3: Austria
  4: Australia
  5: Belgium
  6: Bulgaria
  7: Brazil
  8: Canada
  9: Chile
  10: China
  11: Colombia
  12: Cuba
  13: Czech Republic
  14: Germany
  15: Egypt
  16: France
  17: Gabon
  18: Greece
  19: Hong Kong
  20: Hungary
  21: Indonesia
  22: Ireland
  23: Israel
  24: India
  25: Italy
  26: Japan
  27: Kiribati
  28: Lesotho
  29: Latvia
  30: Madagascar
  31: Mexico
  32: Malaysia
  33: Niger
  34: Netherlands
  35: Norway
  36: New Zealand
  37: Philippines
  38: Poland
  39: Portugal
  40: Romania
  41: Serbia
  42: Russian Federation
  43: Saudi Arabia
  44: Seychelles
  45: Singapore
  46: Slovenia
  47: Slovakia
  48: Thailand
  49: Turkey
  50: Taiwan Province of China
  51: Ukraine
  52: United States
  53: Venezuela
  54: Zambia

country_code:
  1: ae
  2: ar
  3: at
  4: au
  5: be
  6: bg
  7: br
  8: ca
  9: ch
  10: cn
  11: co
  12: cu
  13: cz
  14: de
  15: eg
  16: fr
  17: gb
  18: gr
  19: hk
  20: hu
  21: id
  22: ie
  23: il
  24: in
  25: it
  26: jp
  27: kr
  28: lt
  29: lv
  30: ma
  31: mx
  32: my
  33: ng
  34: nl
  35: no
  36: nz
  37: ph
  38: pl
  39: pt
  40: ro
  41: rs
  42: ru
  43: sa
  44: se
  45: sg
  46: si
  47: sk
  48: th
  49: tr
  50: tw
  51: ua
  52: us
  53: ve
  54: za

